Multiple arraymutation strategies
SanderWassenberg/Faultify-1 pull request #10
Opened 2021-12-07 13:38 UTC by nando520024

2021-12-07 13:46 UTC, RubenHuizenga requested changes
Ik zou de string concatination in ArrayMutation.cs vervangen door interpolatie ($"{string} {andere string}" ipv "string" + "andere string")

2021-12-07 13:51 UTC, RubenHuizenga approved these changes
helemaal toppie

2021-12-08 08:17 UTC, PAhrary approved these changes

2021-12-08 08:18 UTC, SanderWassenberg commented on Faultify.Analyze/Mutation/ArrayMutation.cs
> +        ;
die ; op een nieuwe regel mag wel weer terug naar de regel erboven

2021-12-08 08:30 UTC, SanderWassenberg reviewed
i approb

2021-12-08 08:30 UTC, merged